### ISSUE TITLE
The server continues to run out of disk space

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-dashboard#36]
Both Airflow and the scrapers log pretty aggressively. This is eating a lot of our server disk space. There may yet-to-be-discovered contributors, as well. 

I manually removed the worker logs, and cleaned up some outdated Docker artifacts. Let's reduce the max log age from 30 days to 10, or even 7. (It's really rare that we need logs older than that, as we at least triage issues quickly.)

Also, let's confirm that the DAG is removing any Airflow logs, e.g., for DAGs, as well as for the Airflow processes themselves.

**Comment by hancush** [comment]
Disk use has increased to > 90% again. :-( Let me see what's eating space.

**Comment by hancush** [comment]
As of Friday, the site is down.

**Comment by hancush** [comment]
The log directory is 3.1 GB. Close to 90 percent of that is Airflow logs. It looks like the cleanup jobs are overrepresented in the large directories/files...

```
ubuntu@ip-10-0-0-244:~$ sudo du -sh /var/log/la-metro-dashboard
3.1G	/var/log/la-metro-dashboard
ubuntu@ip-10-0-0-244:~$ sudo du -sh /var/log/la-metro-dashboard/airflow
2.7G	/var/log/la-metro-dashboard/airflow
ubuntu@ip-10-0-0-244:~$ sudo du -ah /var/log/la-metro-dashboard/airflow/*/ | sort -nr | head -n 25
972K	/var/log/la-metro-dashboard/airflow/airflow_log_cleanup/log_cleanup_worker_num_1_dir_0/2020-07-19T00:00:00+00:00
968K	/var/log/la-metro-dashboard/airflow/airflow_log_cleanup/log_cleanup_worker_num_1_dir_0/2020-07-19T00:00:00+00:00/1.log
964K	/var/log/la-metro-dashboard/airflow/windowed_bill_scraping/windowed_bill_scraping/2020-06-24T16:35:00+00:00
960K	/var/log/la-metro-dashboard/airflow/windowed_bill_scraping/windowed_bill_scraping/2020-06-24T16:35:00+00:00/1.log
924K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_TaskInstance/2020-07-06T00:00:00+00:00
920K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_TaskInstance/2020-07-06T00:00:00+00:00/1.log
756K	/var/log/la-metro-dashboard/airflow/daily_scraping/daily_scraping/2020-07-15T13:06:08.948984+00:00
752K	/var/log/la-metro-dashboard/airflow/daily_scraping/daily_scraping/2020-07-15T13:06:08.948984+00:00/1.log
740K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-12T00:00:00+00:00
740K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-10T00:00:00+00:00
736K	/var/log/la-metro-dashboard/airflow/scheduler/2020-07-29/windowed_bill_scraping.py.log
736K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-21T00:00:00+00:00
736K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-14T00:00:00+00:00
736K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-12T00:00:00+00:00/1.log
736K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-10T00:00:00+00:00/1.log
732K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-21T00:00:00+00:00/1.log
732K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-15T00:00:00+00:00
732K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-14T00:00:00+00:00/1.log
732K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-09T00:00:00+00:00
728K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-15T00:00:00+00:00/1.log
728K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-13T00:00:00+00:00
728K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-11T00:00:00+00:00
728K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-09T00:00:00+00:00/1.log
724K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-16T00:00:00+00:00
724K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-13T00:00:00+00:00/1.log
```

**Comment by hancush** [comment]
One thing we could do to reduce the size of the logs is to not log the names of things being deleted. The largest log file has 6.2k+ lines, because it cleaned up so much. I'm also wondering whether the cleanup DAGs clean up their own logs, because some of the dates on these cleanup logs (7/6, 7/9) were more than 14 days ago...

**Comment by hancush** [comment]
There are 17k log files!!!

```
ubuntu@ip-10-0-0-244:~$ sudo du -ah /var/log/la-metro-dashboard/airflow/ | grep "\.log" | wc -l
17383
```

Largest log files:

```
ubuntu@ip-10-0-0-244:~$ sudo du -ah /var/log/la-metro-dashboard/airflow/ | grep "\.log" | sort -nr | head -n 25
968K	/var/log/la-metro-dashboard/airflow/airflow_log_cleanup/log_cleanup_worker_num_1_dir_0/2020-07-19T00:00:00+00:00/1.log
960K	/var/log/la-metro-dashboard/airflow/windowed_bill_scraping/windowed_bill_scraping/2020-06-24T16:35:00+00:00/1.log
920K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_TaskInstance/2020-07-06T00:00:00+00:00/1.log
752K	/var/log/la-metro-dashboard/airflow/daily_scraping/daily_scraping/2020-07-15T13:06:08.948984+00:00/1.log
736K	/var/log/la-metro-dashboard/airflow/scheduler/2020-07-29/windowed_bill_scraping.py.log
736K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-12T00:00:00+00:00/1.log
736K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-10T00:00:00+00:00/1.log
732K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-21T00:00:00+00:00/1.log
732K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-14T00:00:00+00:00/1.log
728K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-15T00:00:00+00:00/1.log
728K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-09T00:00:00+00:00/1.log
724K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-13T00:00:00+00:00/1.log
724K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-11T00:00:00+00:00/1.log
720K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-16T00:00:00+00:00/1.log
708K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_BaseJob/2020-07-19T00:00:00+00:00/1.log
696K	/var/log/la-metro-dashboard/airflow/scheduler/2020-07-29/hourly_processing.py.log
660K	/var/log/la-metro-dashboard/airflow/scheduler/2020-07-29/refresh_guid.py.log
644K	/var/log/la-metro-dashboard/airflow/scheduler/2020-07-29/airflow_log_cleanup.py.log
564K	/var/log/la-metro-dashboard/airflow/windowed_bill_scraping/windowed_bill_scraping/2020-06-24T16:20:00+00:00/1.log
560K	/var/log/la-metro-dashboard/airflow/scheduler/2020-07-29/friday_hourly_scraping.py.log
544K	/var/log/la-metro-dashboard/airflow/scheduler/2020-07-29/airflow_db_cleanup.py.log
528K	/var/log/la-metro-dashboard/airflow/scheduler/2020-07-29/daily_scraping.py.log
472K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_Log/2020-07-08T00:00:00+00:00/1.log
372K	/var/log/la-metro-dashboard/airflow/scheduler/2020-07-29/windowed_event_scraping.py.log
340K	/var/log/la-metro-dashboard/airflow/airflow_db_cleanup/cleanup_BaseJob/2020-07-06T00:00:00+00:00/1.log
```

So it definitely seems like it's death by a thousand tiny cuts, not one log file growing out of control...

**Comment by hancush** [comment]
For reference, the logs for the regular Metro scraper take up a fraction of the space:

```
ubuntu@ip-10-0-0-80:~$ du -ch /tmp/lametro*
1.5M	/tmp/lametro.log
7.0M	/tmp/lametro.log.1
140K	/tmp/lametro.log.10.gz
1.3M	/tmp/lametro.log.11.gz
780K	/tmp/lametro.log.12.gz
512K	/tmp/lametro.log.2.gz
520K	/tmp/lametro.log.3.gz
520K	/tmp/lametro.log.4.gz
488K	/tmp/lametro.log.5.gz
548K	/tmp/lametro.log.6.gz
1.4M	/tmp/lametro.log.7.gz
440K	/tmp/lametro.log.8.gz
4.0K	/tmp/lametro.log.9.gz
15M	total
```

Could we compress older logs, perhaps?

**Comment by hancush** [comment]
Phew, I ran `docker system info` and noticed it said there were 770 containers! So I ran `docker system prune` and...

```
Total reclaimed space: 3.105GB
```

So that should help. I thought I'd configured our containers to be removed once DAGs run, so I'll double check that.

**Comment by hancush** [comment]
When I restarted the application, I noticed the cleanup DAGs weren't turned on!!!!! Turned them on, will update...

**Comment by hancush** [comment]
Update on the log cleanup:

```
[2020-07-31 16:16:11,883] {bash_operator.py:126} INFO - Process will be Deleting 11116 File(s)/Directory(s)
```

Phew! Reclaimed a gig of space:

```
ubuntu@ip-10-0-0-244:~$ sudo du -ch /var/log/la-metro-dashboard
...
2.1G	total
```

**Comment by hancush** [comment]
After the cleanup DAGs ran, and I removed the Docker artifacts, we're back down to 80% disk usage:

```
ubuntu@ip-10-0-0-244:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1.9G     0  1.9G   0% /dev
tmpfs           388M  912K  387M   1% /run
/dev/nvme0n1p1   16G   13G  3.3G  80% /
tmpfs           1.9G  8.0K  1.9G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/loop1       18M   18M     0 100% /snap/amazon-ssm-agent/1566
tmpfs           388M     0  388M   0% /run/user/0
/dev/loop3       29M   29M     0 100% /snap/amazon-ssm-agent/2012
/dev/loop4       97M   97M     0 100% /snap/core/9436
/dev/loop2       97M   97M     0 100% /snap/core/9665
tmpfs           388M     0  388M   0% /run/user/1000
```

Will update with news on the Docker thing.

**Comment by hancush** [comment]
So! It looks like [containers are only removed if their command succeeds](https://github.com/apache/airflow/blob/f1fd3e2c453ddce3e87ce63787598fea0707ffcf/airflow/providers/docker/operators/docker.py#L217-L273). I'm inclined to override this method to intercept this error, remove the container, then raise it, as I don't see any reason to keep failed containers around.

**Comment by hancush** [comment]
We got the alarm again, despite regularly running maintenance DAGs and removing stopped containers.

**Comment by hancush** [comment]
Seems like Airflow creates a bunch of cache files in `/tmp`:

```
ubuntu@ip-10-0-0-244:~$ ls  /tmp/*.__wz_cache | wc -l
3289
```

This has caused the directory to swell to upwards of 1 GB in size. 

```
ubuntu@ip-10-0-0-244:~$ sudo du -sh /tmp/
1.3G	/tmp/
```

We should probably clean these files up!

**Comment by hancush** [comment]
Actually, most (all) of that seems to be concentrated in a cache directory we haven't touched since June:

```
ubuntu@ip-10-0-0-244:~$ ls -lath /tmp/cache/
total 4.9M
drwxrwxrwt 20 root     root     212K Aug  5 20:00 ..
drwxr-xr-x  2 datamade datamade 4.7M Jul 16 18:15 _cache
drwxr-xr-x  4 datamade datamade 4.0K Jun  9 20:11 .
drwxr-xr-x  3 datamade datamade 4.0K Jun  9 20:11 _data
ubuntu@ip-10-0-0-244:~$ du -sh /tmp/cache/_cache/
1.3G	/tmp/cache/_cache/
```

**Comment by hancush** [comment]
I cleaned up the cache dir, using `xargs` because it contained too many files to use `rm` alone:

```
ubuntu@ip-10-0-0-244:~$ find /tmp/cache/_cache -name '*' | xargs sudo rm -v
ubuntu@ip-10-0-0-244:~$ du -sh /tmp/cache/_cache/
100M	/tmp/cache/_cache/
ubuntu@ip-10-0-0-244:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1.9G     0  1.9G   0% /dev
tmpfs           388M  916K  387M   1% /run
/dev/nvme0n1p1   16G   14G  1.9G  88% /
tmpfs           1.9G  8.0K  1.9G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/loop1       18M   18M     0 100% /snap/amazon-ssm-agent/1566
tmpfs           388M     0  388M   0% /run/user/0
/dev/loop3       29M   29M     0 100% /snap/amazon-ssm-agent/2012
/dev/loop4       97M   97M     0 100% /snap/core/9436
/dev/loop2       97M   97M     0 100% /snap/core/9665
tmpfs           388M     0  388M   0% /run/user/1000
```

Looks like we're back below 90% disk use... I'd like to keep an eye out to see if the cache gets out of control again.

**Comment by hancush** [comment]
Also seems like there were some stale images (untagged scraper and Councilmatic images, unused Python, PostGIS, and hello-world images):

```
ubuntu@ip-10-0-0-244:~$ sudo docker image ls
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
datamade/scrapers-us-municipal   staging             a4a9bd408a5a        2 hours ago         498MB
datamade/la-metro-councilmatic   staging             5fc3945d9589        26 hours ago        1.05GB
datamade/la-metro-councilmatic   <none>              0ff9cec15767        7 days ago          1.08GB
datamade/scrapers-us-municipal   <none>              2968e6f1890e        2 weeks ago         534MB
datamade/la-metro-councilmatic   <none>              338fba3810f4        2 weeks ago         1.08GB
python                           3.6-slim-stretch    bfb7cb946c87        5 weeks ago         132MB
hello-world                      latest              bf756fb1ae65        7 months ago        13.3kB
mdillon/postgis                  9.6                 46b6c43824d4        16 months ago       625MB
```

Cleaned those up, and we're down to 68% disk use:

```
ubuntu@ip-10-0-0-244:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1.9G     0  1.9G   0% /dev
tmpfs           388M  916K  387M   1% /run
/dev/nvme0n1p1   16G   11G  5.1G  68% /
tmpfs           1.9G  8.0K  1.9G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/loop1       18M   18M     0 100% /snap/amazon-ssm-agent/1566
tmpfs           388M     0  388M   0% /run/user/0
/dev/loop3       29M   29M     0 100% /snap/amazon-ssm-agent/2012
/dev/loop4       97M   97M     0 100% /snap/core/9436
/dev/loop2       97M   97M     0 100% /snap/core/9665
tmpfs           388M     0  388M   0% /run/user/1000
```

**Comment by hancush** [comment]
For some reason, failed scrape containers are not removed. More specifically, [our code to remove containers even if the command fails](https://github.com/datamade/la-metro-dashboard/pull/43) is executing but trying to remove the wrong (?) container:

```
[2021-04-16 23:58:39,871] {docker.py:263} INFO - Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
[2021-04-16 23:58:41,837] {taskinstance.py:1145} ERROR - 404 Client Error: Not Found ("No such container: da76bcb1f7e44d14c2e35a836eea4daca2744310b2c706b73b0bbacb8713c682")
Traceback (most recent call last):
  File "/home/datamade/la-metro-dashboard/plugins/../operators/blackbox_docker_operator.py", line 47, in _run_image
    return super()._run_image()
  File "/home/datamade/.virtualenvs/la-metro-dashboard/lib/python3.6/site-packages/airflow/providers/docker/operators/docker.py", line 269, in _run_image
    raise AirflowException('docker container failed: ' + repr(result))
airflow.exceptions.AirflowException: docker container failed: {'Error': None, 'StatusCode': 1}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/datamade/.virtualenvs/la-metro-dashboard/lib/python3.6/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/datamade/.virtualenvs/la-metro-dashboard/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/da76bcb1f7e44d14c2e35a836eea4daca2744310b2c706b73b0bbacb8713c682?v=False&link=False&force=False

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/datamade/.virtualenvs/la-metro-dashboard/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 978, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/datamade/.virtualenvs/la-metro-dashboard/lib/python3.6/site-packages/airflow/providers/docker/operators/docker.py", line 307, in execute
    return self._run_image()
  File "/home/datamade/la-metro-dashboard/plugins/../operators/blackbox_docker_operator.py", line 51, in _run_image
    self.cli.remove_container(self.container['Id'])
  File "/home/datamade/.virtualenvs/la-metro-dashboard/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/datamade/.virtualenvs/la-metro-dashboard/lib/python3.6/site-packages/docker/api/container.py", line 992, in remove_container
    self._raise_for_status(res)
  File "/home/datamade/.virtualenvs/la-metro-dashboard/lib/python3.6/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/datamade/.virtualenvs/la-metro-dashboard/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("No such container: da76bcb1f7e44d14c2e35a836eea4daca2744310b2c706b73b0bbacb8713c682")
```

This allowed about 9 GB of containers to build up on the production server. We should address this.
